<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>..\..\..\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>..\..\..\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\BepInEx\interop\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="ILGLib">
      <HintPath>..\..\..\BepInEx\interop\ILGLib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>..\..\..\BepInEx\interop\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
