<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>..\..\..\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>..\..\..\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="R3">
      <HintPath>..\..\..\BepInEx\interop\R3.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.XRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="ILGLib">
      <HintPath>..\..\..\BepInEx\interop\ILGLib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>..\..\..\BepInEx\interop\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\..\BepInEx\interop\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.GPUDriven.Runtime">
      <HintPath>..\..\..\BepInEx\interop\Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\..\BepInEx\interop\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="EPOURP">
      <HintPath>..\..\..\BepInEx\interop\EPOURP.dll</HintPath>
    </Reference>
    <Reference Include="SteamVRLib_Unity.XR.OpenVR">
      <HintPath>lib\SteamVRLib_Unity.XR.OpenVR.dll</HintPath>
    </Reference>
    <Reference Include="SteamVRLib_UnityEngine.XR.Management">
      <HintPath>lib\SteamVRLib_UnityEngine.XR.Management.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\BepInEx\interop\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\..\BepInEx\interop\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="Coffee.CompositeCanvas">
      <HintPath>..\..\..\BepInEx\interop\Coffee.CompositeCanvas.dll</HintPath>
    </Reference>
    <Reference Include="Obi">
      <HintPath>..\..\..\BepInEx\interop\Obi.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\..\BepInEx\interop\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="SteamVRLib_Valve.VR">
      <HintPath>lib\SteamVRLib_Valve.VR.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AssetBundles\custom_asset_bundle" />
    <Compile Remove="backup_*\**" />
  </ItemGroup>

</Project>
